# Site settings
title: firedev.com
author: firedev
email: nick@firedev.com
description: > # this means to ignore newlines until "baseurl:"
  Building the internet one site at a time
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://firedev.com" # the base hostname & protocol for your site
twitter_username: firedev
github_username:  firedev

# Build settings
# permalink: /:title
permalink: /:categories/:title/
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "Rakefile"

collections:
  - projects

tag_title_prefix: ''
tag_title_suffix: ''
tag_dir: ''
highlighter: rouge
