# Site settings
title: firedev.com
email: nick@firedev.com
description: > # this means to ignore newlines until "baseurl:"
  Building the internet one site at a time
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://firedev.github.io" # the base hostname & protocol for your site
twitter_username: firedev
github_username:  firedev

# Build settings
markdown: kramdown
