# Bot configuration parameters.

# Config schema version. Increments for backward-incompatible changes.
schema_version: 3

# Telegram settings.
telegram:
    # Telegram Bot API token.
    token: ""

    # The list of Telegram usernames allowed to chat with the bot.
    # If empty, the bot will be available to anyone.
    usernames: []

    # The list of Telegram usernames allowed to change bot settings.
    # If empty, then no one is allowed to change the settings.
    admins: []

    # The list of Telegram group ids, whose members are allowed to chat with the bot.
    # If empty, the bot will only be available to `telegram.usernames`.
    chat_ids: []

# OpenAI settings.
openai:
    # OpenAI API key.
    api_key: ""

    # OpenAI model name. One of the following:
    # gpt-3.5-turbo | gpt-4
    model: "gpt-3.5-turbo"

    # Model prompt.
    prompt: "Your primary goal is to answer my questions. This may involve writing code or providing helpful information. Be detailed and thorough in your responses."

    # Model parameters.
    # See https://platform.openai.com/docs/api-reference/chat/create for description.
    params:
        temperature: 0.7
        presence_penalty: 0
        frequency_penalty: 0
        max_tokens: 1000

    # Azure OpenAI settings, only required if you are using OpenAI through Azure
    # (https://learn.microsoft.com/en-us/azure/cognitive-services/openai/overview)
    # Refer to the Azure documentation for the values of these parameters.
    # azure:
    #     endpoint: https://example-endpoint.openai.azure.com
    #     version: 2023-03-15-preview
    #     deployment: deployment-name

conversation:
    # The maximum number of previous messages
    # the bot will remember when talking to a user.
    depth: 3

    # The maximum number of messages a user can send during the specified time period.
    # Only applies to users who are not listed in `telegram.usernames`.
    #   `count`  = an integer number of messages (0 = unlimited)
    #   `period` = minute | hour | day
    message_limit:
        count: 0
        period: hour

# Image generation settings.
imagine:
    # Enable/disable image generation:
    #   - none             = disabled for everyone
    #   - users_only       = enabled only for users listed in `telegram.usernames`
    #   - users_and_groups = enabled for both users listed in `telegram.usernames`
    #                        and members of `telegrams.chat_ids`
    enabled: users_only

# Where to store the chat context file.
persistence_path: "./data/persistence.pkl"

# Custom AI commands (additional prompts)
shortcuts:
    bugfix: "Examine the following code. Rewrite it if necessary to fix bugs and various problems. Explain the changes you've made."

    proofread: "Proofread the following text. Correct grammar and punctuation errors. Rephrase if necessary. Make sure the resulting text is clear, concise, and easy to read. Explain the changes you've made."

    summarize: "Explain the following text in simple terms. Use no more than two paragraphs."

    translate: "Translate the following text into English."
